.PHONY: build test clean

all:
	@echo "Please specify a target. Options are: install, run-original, run-simple."

install:
	poetry install

run-original:
	poetry run python src/original.py

run-simple:
	poetry run python src/simple.py
